config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :articles do
    resources :comments
  end

  root 'welcome#index'
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true,
            length: { minimum: 5 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if  @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, 'error') %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text, class: 'redactor' %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<div class="page-center">
  <h3 class="titles">Edit article</h3>

  <%= render 'form' %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<table class="table-center">
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= sanitize article.text.html_safe %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article_path(article),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<hr>

app/views/articles/new.html.erb
<h2 class="titles">New article</h2>
<div class="page-center">
<%= render 'form' %>

<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="page-center">
  <p>
    <%= @article.title %>
  </p>

  <p>
    <%= sanitize @article.text.html_safe %>
  </p>

  <hr>

  <h3 class='titles'>Comments</h3>
  <%= render @article.comments %>

  <h3 class='titles'>Add a comment:</h3>
  <%= render 'comments/form' %>

  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
  <% end %>
  <%= link_to 'Back', root_path %>
</div>